plugins {
    id 'java'
    id("io.qameta.allure") version "4.1.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Source: https://mvnrepository.com/artifact/ch.qos.logback/logback-core
    implementation("ch.qos.logback:logback-core:1.6.1")
    // Source: https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    implementation("ch.qos.logback:logback-classic:1.6.1")
    // Source: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    implementation("org.seleniumhq.selenium:selenium-java:4.46.0")
    // Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    testImplementation("org.junit.jupiter:junit-jupiter-api:6.1.2")
    // Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
    testImplementation("org.junit.jupiter:junit-jupiter-engine:6.1.2")
    // Source: https://mvnrepository.com/artifact/io.qameta.allure/allure-junit-platform
    implementation("io.qameta.allure:allure-junit-platform:2.35.3")
}

allure {
    version = '2.27.0'
    useJUnit5 {
        version = '2.27.0'
    }
}

test {
    useJUnitPlatform()
}